### ISSUE TITLE
Why not use kameleon recipes instead of the autoinstall bash script in the Debian bootstrap stage ?

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon-bootstrap-recipes#4]
Currently steps involve booting the boot2kameleon image with qemu, then to inject inside a few commands (qemu_send_key?) to fetch via http the Debian autoinstall bash script, which is run then to perform virtual disk setup and system bootstrap, and so on.

That looks quite exotic and do not benefit from kameleon syntax.

Was it a special reason you could recall for that choice to not use ssh (sshd daemon) to run command in the boot2kameleon VM and not use kameleon scripting instead of the raw bash script.

**Comment by npf** [comment]
Ok, got it: the boot2kameleon is used for Debian where the install cdrom with kickstart is used for RPM-based OSes. I guess we could actually use Debian netinst CD + preseed also ( @vdanjean ?).

Conclusion: that step is considered a black box.

For ref, can you confirm that the following step are now deprecated and could eventually deleted ?
- qemu/steps/bootstrap/archlinux/arch_bootstrap.yaml
- qemu/steps/bootstrap/debian/debootstrap.yaml

**Comment by npf** [comment]
Also the use of the http service which looks quite weird with Debian is indeed common for RedHat kickstart. Makes sense.

**Comment by SalemHarrache** [comment]
Hi Pierre,

Actually, I was using the qemu-send-keys script to install debian with the pressed files.

It's true that with debootstrap, it was a little overkill, but I have rewritten the recipes to use pressed files again since I think it's more stable to use the iso to install debian (even though we lose other debian branches in the process: sid/testing, etc.).

I also worked on a virtualbox-send-keys version, which allows us to install .iso with virtualbox. We will then have bootstrap recipes for both qemu and virtualbox.

I'll commit this very soon.
